# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera-tabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget, QPushButton, QHBoxLayout
from PyQt5.QtGui import QIcon 
from PyQt5.QtCore import QSize, Qt
from PyQt5.QtCore import Qt

class Ui_Form(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(446, 370)
        self.contenedortabla = QtWidgets.QWidget(Form)
        self.contenedortabla.setGeometry(QtCore.QRect(30, 10, 381, 281))
        self.contenedortabla.setObjectName("contenedortabla")
        self.tabla = QtWidgets.QTableWidget(self.contenedortabla)
        self.tabla.setGeometry(QtCore.QRect(10, 10, 351, 261))
        self.tabla.setStyleSheet("QTableWidget::item {\n"
"    border-bottom: 1px solid rgba(220, 220, 220);\n"
"}\n"
"QHeaderView::section {\n"
"    border-bottom: 1px solid rgba(220, 220, 220);\n"
"}\n"
"\n"
"")
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tabla.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla.setIconSize(QtCore.QSize(62, 70))
        self.tabla.setShowGrid(False)
        self.tabla.setWordWrap(True)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(4)
        self.tabla.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tabla.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabla.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabla.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabla.setItem(0, 3, item)
        self.tabla.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla.horizontalHeader().setDefaultSectionSize(70)
        self.tabla.horizontalHeader().setHighlightSections(False)
        self.tabla.horizontalHeader().setMinimumSectionSize(25)
        self.tabla.horizontalHeader().setStretchLastSection(False)
        self.tabla.verticalHeader().setVisible(False)
        self.tabla.verticalHeader().setDefaultSectionSize(20)
        self.tabla.verticalHeader().setHighlightSections(False)
        self.tabla.verticalHeader().setSortIndicatorShown(False)
        self.scrolltabla = QtWidgets.QScrollBar(self.contenedortabla)
        self.scrolltabla.setGeometry(QtCore.QRect(360, 30, 20, 241))
        self.scrolltabla.setOrientation(QtCore.Qt.Vertical)
        self.scrolltabla.setObjectName("scrolltabla")
        self.aggfila = QtWidgets.QPushButton(Form)
        self.aggfila.setGeometry(QtCore.QRect(270, 310, 56, 17))
        self.aggfila.setObjectName("aggfila")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabla.setSortingEnabled(True)
        item = self.tabla.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tabla.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.tabla.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.tabla.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.tabla.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("Form", "fecha"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("Form", "bpd"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("Form", "diluente"))
        __sortingEnabled = self.tabla.isSortingEnabled()
        self.tabla.setSortingEnabled(False)
        item = self.tabla.item(0, 1)
        item.setText(_translate("Form", "18-02-2013"))
        item = self.tabla.item(0, 2)
        item.setText(_translate("Form", "15000"))
        item = self.tabla.item(0, 3)
        item.setText(_translate("Form", "8000"))
        self.tabla.setSortingEnabled(__sortingEnabled)
        self.aggfila.setText(_translate("Form", "agregar fila"))
        
    def columnaedicion(self,accion,ruta,producto,esquema,tabla):
        #Agrega una columna de botones a la tabla, con un botón en cada fila.
        #accioneditar: accion al presionar
        
        num_filas = self.tabla.rowCount()
        num_columnas = self.tabla.columnCount()

        # Agregar columna para los botones
        self.tabla.setColumnCount(num_columnas + 1)
        self.tabla.setHorizontalHeaderItem(num_columnas, QTableWidgetItem("Acción"))

        for fila in range(num_filas):
            # Crear botón
            boton = QPushButton("Accionar")
            boton.setIcon(QIcon(ruta))  # Cambia la ruta por tu imagen
            boton.setIconSize(QSize(32, 32))  # Tamaño del ícono
            boton.clicked.connect(lambda _, ifila=fila: accion(ifila,producto,esquema,tabla))  # Conectar a función con índice de fila

            # Agregar botón a la celda
            widget_boton = QWidget()
            layout_boton = QHBoxLayout(widget_boton)
            layout_boton.addWidget(boton)
            layout_boton.setAlignment(boton, Qt.AlignCenter)
            layout_boton.setContentsMargins(0, 0, 0, 0)
            widget_boton.setLayout(layout_boton)

            self.tabla.setCellWidget(fila, num_columnas, widget_boton)
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
